### ISSUE TITLE
Still missing eGauge 792 completely

### ISSUE THREAD

**Issue by eileenpeppard** [erdl/legacy-scrape-util#15]
Hey, Gang.

I can't access it and the cron job has not gotten it. Can a mini cron job be set up to check this egauge every 5 minutes and if it succeeds, get all the data dating back to 2017-08-12 12:00 ?  The eGuard says it's online at some point during each hour period 96% of the time. Hard to believe, but we are just not getting the data.

Eileen

**Comment by carlosparadis** [comment]
Continuation of some of the problems of issue #12.

@ryantanaka @jygh98 Where did we stop on the crontab saga to choose our own time requests? Do you remember? I see we ended up not moving to the wiki. Also, as far as I recollect scrape-util is executed by a single script bound to the hourly cron job. We would need to deploy an entire new project just for e792. Is this correct?

**Comment by eileenpeppard** [comment]
Hi, guys, update: I do have data from 9/19 16:18 until now. **I'm missing data from 8/12 12:00 to 9/19 16:18**.

(sorry about that. i don't know why the data did not show up in my Tableau.)

**Comment by carlosparadis** [comment]
@eileenpeppard In my summary at the end of #12 I took note that:

> e792 will be missing correct data up to today (October 4, 2017) at 5 PM. While troubleshooting e792, which to my understanding is dedicated solely to PV, Eileen realized her equations for the CTs were incorrect. Originally it's 2 CTs were supposed, to sum up in what would be our PV Power (kW). However, the equation was of subtraction between the CTs, thus canceling them out leading to values close to 0. As such, anything that looks like to 0 is incorrect from any point of.
There is currently no conventional way to flag this in the database such as a quality check column. Maybe this can be considered down the road.

However, you are requesting data before 9/4 - 5 PM. What am I missing here?

**Comment by eileenpeppard** [comment]
oh.... yeah. Shoot! I forgot about that. Good thing you are documenting this. I will take note in the database. Thanks!

**Comment by carlosparadis** [comment]
@eileenpeppard No problem. I am marking the issue as invalid. Feel free to reopen if you find something else missing associated to e792.
