### ISSUE TITLE
Can you check this sensor is in scrape util for dhhl hobo script?

### ISSUE THREAD

**Issue by eileenpeppard** [erdl/legacy-scrape-util#16]
Hi, Guys.

I did not deploy this in house 2 but will now deploy it to replace a bad sensor in house 8. I just want to check that it still exists in the json file.  Hobo SN 9796090
![dhhl hobo in scrape-util](https://user-images.githubusercontent.com/29083044/32579830-bf327582-c486-11e7-9812-c0d4b75180af.PNG)

![2017011-09 house 8 masterbed sensor replacement](https://user-images.githubusercontent.com/29083044/32579902-fb05b024-c486-11e7-8167-487f48f9e0b0.PNG)

**Comment by carlosparadis** [comment]
For the sake of completeness: I confirmed in the office today with you that they are already added to the config, so no changes on the scripting end. 

Config file is located at: /var/local/scrape-util/projects/dhhl-hobo-u12
