### ISSUE TITLE
need to document layout of scrape-util on IT-VM server

### ISSUE THREAD

**Issue by ryantanaka** [erdl/legacy-scrape-util#18]
In response to our confusion in #10, create a diagram similar to what was done for `scrape-util` [here](https://github.com/erdl/survey_display/issues/3). 

- show what symbolic links point to
- illustrate pulling data from various API/sensors, saving raw data on disk as csv's, then placement into postgres db
- show where scrape-util is called (`/etc/cron.hourly`)
- show what folders scrape-util uses
- keep xml file saved here

@carlosparadis, when you get the chance can you add me to this repo so i can assign this to me

**Comment by ryantanaka** [comment]
@carlosparadis, @jygh98 can you guys give some feedback? I think it's a little messy with all those arrows (but then again the program is a little messy too hah). Thanks
![scrape_util_diagram 1](https://user-images.githubusercontent.com/19616012/34135559-7fd63740-e405-11e7-8382-0eabf14ff532.png)

**Comment by ryantanaka** [comment]
12/19/17 conf call notes:

> - divide current image in 3 blocks
[12:35] 
1st block) database+io folders (call it io folders if you like, no need to map every single godamn folder)
[12:35] 
2nd block) src code. It is the one already there with the chain of soft links. just draw a rectangle or something on it
[12:36] 
3rd block) it is not included currently in the image. add some folder icon saying configs. No need to also look into all possible files, its more as a reminder in this figure it is a big chunk of concern in scrape-util
[12:37] 
4th) make sure to check that the folder where the hobo, egauge, webctrl icons point right now, shouldnt actually be the scrape util file, as i believe that contrary to survey display the order is first scrape util, and the output is just as a memory of the operation when specified on the config file, rather than how survey display does which first saves the file to then hope for scrape util to stop by
[12:38] 
5th) maybe we want to revisit given the new diagram how we point its 3 portions in the terminal figures and how this mess is organized currently (or maybe we dont, after we change this, we likely will want to keep the figure of the old way apart as memory, and keep the new simplified version together in this diagram)

referring to the following diagram:
![scrape_util_diagram 2](https://user-images.githubusercontent.com/19616012/34184006-bb27a498-e4c1-11e7-89ab-68f2a3b20aa3.png)

I'll be updating the diagram based on what was discussed above.

**Comment by ryantanaka** [comment]
update 12/21:

3 main blocks included:
- `scrape-util` source
- outputs
- configs 

APIs also point to where they should. 

I'm going to get scrape-util running on my computer so that I can do some debugging (will just use fake data, fake sensors, whatever). A handful of the code is understandable but there are some areas where terrible naming conventions, **_overuse_** of every possible fancy python capability imaginable, and not so descriptive comments make it impossible unless i have print statements telling me whats going on. 

Here is the updated diagram: 

![scrape_util_diagram 5](https://user-images.githubusercontent.com/19616012/34282627-0de79102-e66b-11e7-9b4e-304589e9e91b.png)

**Comment by ryantanaka** [comment]
conf. call 12/22 notes:

- split diagram into two separate images (top vs bottom)
- as of **Dec 19, 2017 we started using 5 minute intervals for retrieving data** instead of 1 hour (will post this on the diagram)
- regarding toml files
    - need to express that they can show up in different forms (for example: egauge.toml, psql-config.toml, value-remap.toml, etc..) 
    - need to express that they can refer to other toml files 
    - for project-nameN, show how HOBO data can be manually inserted
    - for project-name2, add more detail to the config.toml files
        - show that there can be two types of errors 
        - for example: `/var/local/scrape-util/errors/hobo-u12` and `/var/local/scrape-util/hobo-u12/errors`

**Comment by ryantanaka** [comment]
updated 12/27:

![scrape_util_diagram 7](https://user-images.githubusercontent.com/19616012/34393908-102d99be-eafa-11e7-8142-8cf2df545c83.png)

[Scrape_Util_diagram (3).xml.zip](https://github.com/erdl/legacy-scrape-util/files/1589917/Scrape_Util_diagram.3.xml.zip)

**Comment by ryantanaka** [comment]
scrape-util layout on server:
![scrape_util_layout 1](https://user-images.githubusercontent.com/19616012/34425794-9210d3ea-ebd3-11e7-83e7-235c048740e2.png)

scrape-util diagram:
![scrape_util_diagram 8](https://user-images.githubusercontent.com/19616012/34425814-e6dbfe86-ebd3-11e7-8c5e-b94ca16592c1.png)

[Scrape_Util_diagram (4).xml.zip](https://github.com/erdl/legacy-scrape-util/files/1592309/Scrape_Util_diagram.4.xml.zip)

**Comment by carlosparadis** [comment]
For the record, @kathrynparadis will be adding some of the diagram on item 3 for the HOBO on [this issue](https://github.com/erdl/sensors/issues/9).

**Comment by ryantanaka** [comment]
Updated:

![scrape_util_diagram](https://user-images.githubusercontent.com/19616012/34898780-f94966c8-f798-11e7-964c-493372dce486.png)

[Scrape_Util_diagram.xml.zip](https://github.com/erdl/legacy-scrape-util/files/1627776/Scrape_Util_diagram.xml.zip)

**Comment by ryantanaka** [comment]
This is done. Diagrams are located in the wiki. Closing this issue.
