### ISSUE TITLE
document what we currently understand about scrape-util

### ISSUE THREAD

**Issue by ryantanaka** [erdl/legacy-scrape-util#20]
- document current understanding of the program layout and usage
- move to wiki

- draft will be here

**Comment by ryantanaka** [comment]
# Scrape-Util Layout

## `tmp/`

The `tmp` directory contains folders for storing data and information output by the program. It also contains a projects folder, which contains configuration and state files for each individual project. The current layout of the `tmp` directory is as follows:

**Comment by ryantanaka** [comment]
`/tmp` folder semantics diagram.. WIP

![folder_semantics](https://user-images.githubusercontent.com/19616012/35242767-a50337ce-ff5e-11e7-92fd-d607f9b9c345.png)

**Comment by ryantanaka** [comment]
@carlosparadis @jygh98 

Hey gang, 

When you guys get the change, can you glance over the wiki above and give me some suggestions for anything that could be missing, inconsistencies, etc.?

@carlosparadis can you add me to this repo, then I can transition the comment over to the wiki page.

thanks

**Comment by carlosparadis** [comment]
@ryantanaka done

**Comment by ryantanaka** [comment]
@carlosparadis , thanks

See in [wiki](https://github.com/erdl/legacy-scrape-util/wiki/Current-Program-Layout)

**Comment by ryantanaka** [comment]
Everything has been moved over to the wiki. Closing this issue.
