### ISSUE TITLE
Outdoor lights labelled wrong in database, Eileen corrected

### ISSUE THREAD

**Issue by eileenpeppard** [erdl/legacy-scrape-util#31]
Hi, Guys. NO ACTION NEEDED. Just recording for reference

Jim just installed the outdoor lights, so we should be getting data and are not.
ABSPATH:1:#powerscout_frog_1f/kw_avg_phase_a_tn
ABSPATH:1:#powerscout_frog_2f/kw_avg_phase_a_tn

Data was labeled wrong in the database. These lights are actually mapped to powerscount F phase A and the database had outdoor lights mapped to E phase A.  I will rename it in the database.
Purpose IDs:
92 and 105 were originally listed as exterior lights, will rename unknown. All data is zero.
90 and 103 were originally listed as lutron-lights and we be renamed exterior-lights

**Comment by carlosparadis** [comment]
@eileenpeppard If you need, I can find out on the server what is the ABSPATH of purpose id 92 and 105, so you can locate the sensors in webctrl instead of leaving them as "unknown". Let me know.

**Comment by eileenpeppard** [comment]
I know the abspath, I don't know what the current transducers are measuring in the building - on the circuit breakers. There's no problem on your end.
