### ISSUE TITLE
Create Notebook to pull past data in WebCtrl Module

### ISSUE THREAD

**Issue by jygh98** [erdl/legacy-scrape-util#5]
This is a continued effort to create scripts to acquire past data when the problem occurs. #1 handled missing `egauge` data. This notebook will handle the `webctrl` acquisition module of scrape-utils, which is used by the `uhm_frog` project.

**Comment by carlosviansi** [comment]
Here are the links:

https://github.com/alclabs/BulkTrendServer

The one you should focus on: https://github.com/alclabs/BulkTrendClient

The Server is installed on webctrl as a plug-in, and is what enables the API so the client can pull the data. Right now the webctrl UI is offline for whatever reason beyond my understanding, but the API should be online or we would be losing data.

**Comment by jygh98** [comment]
# Project Dependencies
## Jupyter Notebook
In my case I download Anaconda which came with a bunch of preinstalled programs like Jupyter Notebook, otherwise you can directly download it alone.

## Create /tmp Folders
From the server, move the appropriate project folders into a new /tmp folder located within the notebook module.  However, you will need to delete the following line

    is-active = true

from the config.toml /webctrl-config.toml.  This would be found within the [settings] header

## Python
You may be required to install the toml library in the event you run into 

    ModuleNotFoundError: No module named 'toml'

Installing [toml 0.9.2](https://pypi.python.org/pypi/toml) and moving the toml.py file into the notebook module has worked.

**Comment by jygh98** [comment]
```
import requests

apiuser = '<apiuser>'
apipass = '<apipass>'
uri = 'http://www.soest.hawaii.edu/hneienergy/bulktrendserver/read'
params = {'id': 'ABSPATH:1:#frog1_duct_sensors_1/m030', 'start': '2017-09-13', 'end': '2017-09-13', 'format': 'json'}



auth = (apiuser, apipass)
req = requests.post(uri, params = params, auth=tuple(auth))
return req.json()[0]['s']
```

**Comment by carlosviansi** [comment]
;-) So glad we have this out now, good job on teasing this out of that code. I will go ahead and take the torch from here and make a Notebook out of it. 

For my own record, [the link that contains the documentation for the API](http://hneienergy.soest.hawaii.edu/bulktrendserver/doc.html) right now is behind login/password from WebCTRL. I am planning on moving this out to a wiki if we can't figure anything else. From what I gather, Jim will need it anyway for his collaborators on next week.

**Comment by carlosviansi** [comment]
This issue will continue on the sensor project, where the notebook will be created, and therefore I am closing it here.
