### ISSUE TITLE
Create Notebook to pull past data from HOBO

### ISSUE THREAD

**Issue by carlosparadis** [erdl/legacy-scrape-util#7]
I think this is a worthwhile exercise to see how the HOBO module is implemented with the different folders. 

There was one particular incident where Eileen put the data of one project in the other. Thankfully it seems an error was thrown due to mismatch of columns, but this may not always be the case.

When you are done with the other notebooks, this may be a good follow-up step.

**Comment by carlosviansi** [comment]
I will put this issue on hold until we go over the handle of error mechanisms #9.

**Comment by carlosparadis** [comment]
@kathrynparadis [is working on documenting how to find missing data and diagnose errors on the wiki](https://github.com/erdl/sensors/issues/9), since this is not necessarily something we would be automated in a notebook, like the other sensors where there is an API to pull data from the source. 

Therefore, I am closing this issue.
